p3 : player.o board.o p2.cpp
	g++ p3.cpp board.o player.o  -std=c++11 -Wall -g -o p3

board.o : board.h board.cpp
	g++ board.cpp                -std=c++11 -Wall -g -c

player.o : player.h player.cpp
	g++ player.cpp               -std=c++11 -Wall -g -c
